stft:
  n_fft: 1024
  win_length: 1024
  hop_length: 256
  power: 1
  center: True
mel:
  n_mels: 80
  sample_rate: ${sample_rate}
  f_min: 0
  f_max: 8000
  n_stft: 513 #${preprocess.stft.n_fft} // 2 + 1
  norm: "slaney"
  mel_scale: "slaney"

audio:
  sample_rate: ${sample_rate}
defaults:
  - preprocess_dataset: JSUT


train_tar_sink:
  _target_: webdataset.ShardWriter
  pattern: "preprocessed_data/JSUT/JSUT-train-%06d.tar.gz"
val_tar_sink:
  _target_: webdataset.ShardWriter
  pattern: "preprocessed_data/JSUT/JSUT-val-%06d.tar.gz"
val_size: 500

stats_path: preprocessed_data/JSUT/stats.json
speakers_path: preprocessed_data/JSUT/speakers.json
vocab_path: preprocessed_data/JSUT/vocab.txt
accent_vocab_path: preprocessed_data/JSUT/accent_vocab.txt

pitch_phoneme_averaging: True
energy_phoneme_averaging: True